import Head from 'next/head'
import { useState } from 'react'
import Link from 'next/link';


export default function Home() {

  const [fname, setfname] = useState('');
  const [lname, setlname] = useState('');
  const [gender, setgender] = useState('Gender not specified');
  const [contactno, setcontactno] = useState('');
  const [regno, setregno] = useState('');
  const [branch, setbranch] = useState('');
  const [srmid, setsrmid] = useState('');
  const [github, setgithub] = useState('');
  const [linkin, setlinkin] = useState('');
  const show = { fname: fname, lname: lname, gender: gender, contactno: contactno, regno: regno, branch: branch, srmid: srmid, github: github, linkin: linkin };
  const handleSubmit = (e) => {
    e.preventDefault();
    console.log(show);
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className="form" onSubmit={handleSubmit}>
        <div className="form-header">
          KzForms
        </div>
        <div className="form-body">
          <div className="form-name">
            <div className="form-fname">
              <label htmlFor="fname" className="form-label">
                First Name<br></br>
                <input type="text" id="fname" required className="form-input" value={fname} onChange={(e) => setfname(e.target.value)}></input>
              </label>
            </div>
            <div className="form-lname">
              <label htmlFor="lname" className="form-label">
                Last Name<br></br>
                <input type="text" id="lname" required className="form-input" value={lname} onChange={(e) => setlname(e.target.value)}></input>
              </label>
            </div>
          </div>
          <div className="gender-contactno">
            <div className="form-gender">
              <label htmlFor="gender" className="form-label">
                Gender<br></br>
                <select className="gender-dropdown" id="gender" value={gender} onChange={(e) => setgender(e.target.value)}>
                  <option value="">Select your gender</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                  <option value="Other">Other</option>
                </select>
              </label>
            </div>
            <div className="form-contactno">
              <label htmlFor="contactno" className="form-label">
                Contact Number<br></br>
                <input type="text" id="contactno" required className="form-input" value={contactno} onChange={(e) => setcontactno(e.target.value)}></input>
              </label>
            </div>
          </div>
          <div className="form-regno">
            <label htmlFor="regno" className="form-label">
              Registration Number<br></br>
              <input type="text" id="regno" required className="form-input" value={regno} onChange={(e) => setregno(e.target.value)}></input>
            </label>
          </div>
          <div className="form-branch">
            <label htmlFor="branch" className="form-label">
              Branch<br></br>
              <input type="text" id="branch" className="form-input" value={branch} onChange={(e) => setbranch(e.target.value)}></input>
            </label>
          </div>
          <div className="srm-mail-id">
            <label htmlFor="srm-email" className="form-label">
              SRMIST Email Id<br></br>
              <input type="email" id="srm-email" required className="form-input" value={srmid} onChange={(e) => setsrmid(e.target.value)}></input>
            </label>
          </div>
          <div className="github">
            <label htmlFor="git" className="form-label">
              GitHub Profile Link<br></br>
              <input type="url" id="git" className="form-input" value={github} onChange={(e) => setgithub(e.target.value)}></input>
            </label>
          </div>
          <div className="linkin-prof">
            <label htmlFor="linkin" className="form-label">
              Linkin Profile Link<br></br>
              <input type="url" id="linkin" className="form-input" value={linkin} onChange={(e) => setlinkin(e.target.value)}></input>
            </label>
          </div>
          <div className="radio-button">
            <input type="radio" value="none" id="radio-1" className="radio-input"></input>
            <label htmlFor="radio-1" className="radio-label">I agree to the terms & conditions</label>
            <br></br>
            <input type="radio" value="none" id="radio-2" className="radio-input"></input>
            <label htmlFor="radio-2" className="radio-label">All the information given above are true to the best of my knowledged</label>
          </div>
          <div className="form-button">
            <Link
              href={{
                pathname: "/result",
                query: show // your data array of objects
              }}>
              <button type="submit" className="button" href="https://stackoverflow.com/questions/58116211/how-to-redirect-to-another-page-on-button-click-in-reactjs">Submit</button>
            </Link>
          </div>
        </div>
      </form>

    </div>
  )
}
